planner_variables:

  heuristic: SoftConstraint  # Types: TrustRegion, SoftConstraint, TimeOptimization #
  n_act_eefs: 2
  time_step: 0.1
  time_horizon: 9.5
  external_force: [0.00, 0.00, 0.00]
  com_displacement: [0.20, 1.05, 0.6]
  num_com_viapoints: 0
  com_viapoints:
    via0: [2.50,    0.500, 0.45,  0.00]

  max_time_iterations: 100
  max_time_residual_tolerance: 1e-3
  min_time_residual_improvement: 1e-5

  gravity: 9.81
  robot_mass: 60.00
  friction_coeff: 1.0
  friction_cone: LinearCone  # Types: LinearCone, SocCone #
  torque_range: [-200.0, 200.0]
  eff_offset_rf: [ 0.00,  0.00,  0.00]
  eff_offset_lf: [ 0.00,  0.00,  0.00]
  eff_offset_rh: [ 0.20,  0.00,  0.48]
  eff_offset_lh: [-0.20,  0.00,  0.48]
  cop_range_rf: [-0.03,  0.03, -0.08,  0.08]
  cop_range_lf: [-0.03,  0.03, -0.08,  0.08]
  cop_range_rh: [-0.03,  0.03, -0.03,  0.03]
  cop_range_lh: [-0.03,  0.03, -0.03,  0.03]
  max_eef_lengths: [0.82,  0.82,  0.60,  0.60]

  w_trq_arm:       1.000
  w_trq_leg:       1.000
  w_com:           [ 10000,  10000,  10000]
  w_amom:          [ 0.500,  0.500,  0.500]
  w_lmom:          [ 0.010,  0.001,  0.001]
  w_amomd:         [ 0.100,  0.400,  0.100]
  w_lmomd:         [ 0.015,  0.015,  0.015]
  w_amom_final:    [ 10.00,  10.00,  10.00]
  w_lmom_final:    [ 10.00,  10.00,  10.00]
  w_com_via:       [ 0.000,  0.000,  0.000]
  w_frc_arm:       [ 0.001,  0.001,  0.001]
  w_frc_leg:       [ 0.001,  0.001,  0.001]
  w_dfrc_arm:      [ 0.000,  0.000,  0.000]
  w_dfrc_leg:      [ 0.000,  0.000,  0.000]
  w_amom_track:    [ 1.000,  1.000,  1.000]
  w_lmom_track:    [ 0.100,  0.100,  0.100]


  store_data: True
  use_default_solver_setting: True
